version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    container_name: recipe_app_db
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: recipe_app_drf
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
      - dev-static-data:/vol/web
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=admin
    depends_on:
      - db

volumes:
  dev-db-data:
  dev-static-data: